version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      # 登录ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 827117942915.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - echo npm install completed on `date`
      - npm run build
      - echo npm run build completed on `date`

      # 用当前时间作为tag 获取日期作为标签
      - TAG=$(date +%Y%m%d%H%M%S)
      # build构建镜像(镜像名直接设置成ECR规定的名字)
      - docker build -t 827117942915.dkr.ecr.ap-northeast-1.amazonaws.com/re228:$TAG ./
      - echo docker build completed on 
      # 推送镜像
      - docker push 827117942915.dkr.ecr.ap-northeast-1.amazonaws.com/re228:$TAG
      - echo docker push completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      # 生成给ECS使用的imagedefinitions.json name必须和タスク中的容器名字一样的
      - printf '[{"name":"containerName","imageUri":"%s"}]' 827117942915.dkr.ecr.ap-northeast-1.amazonaws.com/re228:$TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
